jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v2
      - id: get_version
        name: Set globals
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=ADDON_VERSION::${GITHUB_REF/refs\/tags\/v/}
          echo ::set-output name=CLASSIC_INTERFACE::11306
      - env:
          ADDON_VERSION: '${{ steps.get_version.outputs.ADDON_VERSION }}'
          INTERFACE: '${{ steps.get_version.outputs.CLASSIC_INTERFACE }}'
        name: Set TOC
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: '["PriorityLootList/PriorityLootList.toc", "PriorityLootList/main.lua"]'
          tokenPrefix: '${'
          tokenSuffix: '}'
      - name: Build project
        run: |
          zip -r PriorityLootList-${{ steps.get_version.outputs.VERSION }}-classic.zip PriorityLootList
      - env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        id: create_release
        name: Create Release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: 'Release ${{ steps.get_version.outputs.VERSION }}'
          tag_name: '${{ steps.get_version.outputs.VERSION }}'
      - env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        id: upload-release-asset
        name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          asset_content_type: application/zip
          asset_name: 'PriorityLootList-${{ steps.get_version.outputs.VERSION }}-classic.zip'
          asset_path: './PriorityLootList-${{ steps.get_version.outputs.VERSION }}-classic.zip'
          upload_url: '${{ steps.create_release.outputs.upload_url }}'
name: Upload Release Asset
'on':
  push:
    tags:
      - v*